# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 7b0df4e0004a526c4e6d3dd0148b42f16a4c7c9475b43eea05bb5844b959eb674e984cd01d687d2bcb505784d5f88b050a37dfa7da3c7f955c656a4b2f9f603b

test:
  secret_key_base: a26a8d71a43739a006c768ea613396b19c699211767c122873060dda1ee41a8542b3da037d6fdb2e87c0c60a260dbace0f63e602ab5ee38b6afae3dd3e11da62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
